apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-node-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-node-2
  template:
    metadata:
      labels:
        app: storage-node-2
    spec:
      containers:
      - name: storage-node-2
        image: rishichirchi/storage-node-2:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: storage-node-2
spec:
  selector:
    app: storage-node-2
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: NodePort
